spring:
  application:
    name: bank-frontUI-service
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}/protocol/openid-connect/token
        registration:
          yandex:
            provider: keycloak
            client-id: yandex-bank
            client-secret: TIMXnhuV51qTYQrgGcZZQIgLpECAxAC2
            authorization-grant-type: client_credentials
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: yandex
      client:
        config:
          default:
            logger-level: full
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  http:
    codecs:
      log-request-details: true

server:
  port: 8090
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${ZIPKIN_PROBABILITY:1}

exchange:
  rates:
    url: ${EXCHANGE_RATES_URL:http://exchange/rates}