spring:
  application:
    name: frontUI
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8085/realms/master/protocol/openid-connect/token
#            http://localhost:8085/realms/master/protocol/openid-connect/token
#            http://localhost:8080/realms/demo/protocol/openid-connect/token
        registration:
          yandex:
            provider: keycloak
            client-id: yandex-bank
            client-secret: TIMXnhuV51qTYQrgGcZZQIgLpECAxAC2
#            scope: resource.read
            authorization-grant-type: client_credentials
  # datasource:
 #   driver-class-name: org.postgresql.Driver
 #   url: jdbc:postgresql://localhost:5433/yandex_bank?currentSchema=front
 #   username: postgres
 #   password: postgres
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: yandex
      client:
        config:
          default:
            logger-level: full
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
      config:
        enabled: false
        defaultContext: application

 # liquibase:
 #   enabled: true
 #   change-log: db/changelog/changelog.yaml
 #   default-schema: front

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org:
      springframework:
        security: DEBUG
