spring:
  application:
    name: frontUI
 # datasource:
 #   driver-class-name: org.postgresql.Driver
 #   url: jdbc:postgresql://localhost:5433/yandex_bank?currentSchema=front
 #   username: postgres
 #   password: postgres
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
      config:
        enabled: false
        defaultContext: application

 # liquibase:
 #   enabled: true
 #   change-log: db/changelog/changelog.yaml
 #   default-schema: front

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org:
      springframework:
        security: ERROR
