spring:
  application:
    name: bank-blocker-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}
  config:
    import: optional:consul:${consul_host:localhost}:8500

server:
  port: 8088

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${ZIPKIN_PROBABILITY:1}