spring:
  application:
    name: bank-exchangeGenerator-service

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    default-schema: exchange

  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}/protocol/openid-connect/token
        registration:
          yandex:
            provider: keycloak
            client-id: yandex-bank
            client-secret: TIMXnhuV51qTYQrgGcZZQIgLpECAxAC2
            #            scope: resource.read
            authorization-grant-type: client_credentials

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    admin:
      client-id: exchange-generator
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "0"
      retries: 0

server:
  port: 8086

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${ZIPKIN_PROBABILITY:1}

kafka:
  topic: ${KAFKA_TOPIC:exchange-rates-topic}
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG