spring:
  application:
    name: bank-transfer-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}

resilience4j:
  retry:
    instances:
      checkTransaction:
        max-attempts: 3
        wait-duration:
          seconds: 1
      transfer:
        max-attempts: 3
        wait-duration:
          seconds: 1

server:
  port: 8087

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
