apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-blocker-service.fullname" . }}
  labels:
    {{- include "bank-blocker-service.labels" . | nindent 4 }}
data:
  suspect-amount: {{ tpl .Values.config.suspect_amount . | quote }}