spring:
  application:
    name: bank-cash-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    admin:
      client-id: cash
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "all"
      retries: 3

server:
  port: 8083

resilience4j:
  retry:
    instances:
      checkTransaction:
        max-attempts: 3
        wait-duration:
          seconds: 1

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${ZIPKIN_PROBABILITY:1}

kafka:
  topic: ${KAFKA_TOPIC:notifications-topic}