spring:
  application:
    name: cash
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
      config:
        enabled: false
        defaultContext: application
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/master
server:
  port: 8083