spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/yandex_bank?currentSchema=accounts
    username: postgres
    password: postgres
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
      config:
        enabled: false
        defaultContext: application

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    default-schema: accounts

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8085/realms/master

server:
  port: 8082

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#        boot:
#          web: DEBUG
#      apache:
#        coyote: DEBUG
#        http: DEBUG