apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "bank-notifications-service.labels" . | nindent 4 }}
data:
  KAFKA_TOPIC: {{ .Values.config.KAFKA_TOPIC | quote }}