{
 "title": "Bank metrics",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Login rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(user_logins_success_total[10m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(user_logins_failure_total[10m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "blocker rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(transaction_blocker_total[10m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Time since last successful import",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exchange_success_import_time" }
   ]
  }
 ]
}