spring:
  application:
    name: notifications
#  cloud:
#    consul:
#      host: ${consul_host:localhost}
#      port: 8500
#      discovery:
#        hostname: notifications
#        prefer-ip-address: false
#        health-check-url: http://${spring.cloud.consul.discovery.hostname}:${server.port}/actuator/health
#      config:
#        enabled: false
#        defaultContext: application

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}

server:
  port: 8092