spring:
  application:
    name: bank-notifications-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    admin:
      client-id: notifications
      fail-fast: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notifications
#      properties:
#        spring.json.value.default.type: "ru.yandex.practicum.tarasov.notifications.DTO.NotificationDto"
#        spring.json.trusted.packages:
#          - ru.yandex.practicum.tarasov.accounts.DTO
#          - ru.yandex.practicum.tarasov.transfer.DTO
#          - ru.yandex.practicum.tarasov.cash.client.notifications.dto
#          - ru.yandex.practicum.tarasov.notifications.DTO

server:
  port: 8092

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

kafka:
  topic: ${KAFKA_TOPIC:"notifications-topic"}