spring:
  application:
    name: bank-exchange-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:yandex_bank}?currentSchema=${DB_SCHEMA:exchange}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${postgres-password:postgres}

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    default-schema: exchange

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8085/realms/master}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    admin:
      client-id: exchange
      fail-fast: true
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: exchange

server:
  port: 8084

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health

kafka:
  topic: ${KAFKA_TOPIC:"exchange-rates-topic"}
